language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.6-dev"
 - "3.7-dev"

addons:
  apt:
    packages:
        gettext  # This was removed in the Precise release on

matrix:
  allow_failures:
    python:
        - "3.6-dev"
        - "3.7-dev"

install:
    - pip install --upgrade pip
    - pip install coveralls coverage

script: coverage run --include=bagit.py setup.py test

after_success:
    coveralls
